baseURL         : "https://anudeepsamaiya.github.io/"
title           : "Asymptote - Personal website of Anudeep Samaiya"
author          : "Anudeep Samaiya"
languageCode    : "en-us"
theme           : "cocoa"
publishdir      : "public"
license         : "MIT"
licenselink     : "https://github.com/anudeepsamaiya/anudeepsamaiya.com/blob/master/LICENSE"

menu:
  main:
  # - identifier  : running
  #   name        : Running
  #   url         : /reading/
  #   weight      : -130

  - identifier  : reading
    name        : Reading
    url         : /reading/
    weight      : -120

  - identifier  : writing
    name        : Writing
    url         : /writing/
    weight      : -110

  # - identifier  : listening
  #   name        : Listening
  #   url         : /listening/
  #   weight      : -100

  - identifier  : about
    name        : About
    url         : /about/
    weight      : -90

params:
  lang                : "en"
  author              : "Anudeep Samaiya"
  # appears in the site header when set to a non-empty string
  selfintro           : >
    I'm a programmer/backend developer. I help great startups build scalable backend systems.
    I read books on fiction, economics, math, physics and about space. I also watch movies
    and listen to music, Led Zeppelin is my favorite band.
  # selfintro         : "I am a programmer/python developer. A Space geek, marathoner Interested in computers, math, economics, physics and philosophy."
  description         : "Keep Breathing, innnn and aaaooout, repeat"
  latestpostscount    : 3                             # how many posts to display on the home page
  copyright           : "Copyright © 2018 Anudeep Samaiya"

  email               : "anudeepsamaiya@gmail.com"
  github              : "//github.com/anudeepsamaiya"
  linkedin            : "//linkedin.com/in/anudeepsamaiya"
  twitter             : "//twitter.com/anudeepsamaiya"
  instagram           : "//instagram.com/anudeepsamaiya"
  px500               : "//500px.com/anudeepsamaiya"
  include_rss         : false                         # include RSS <link> tag in <head> and show RSS icon

  # logofile            : "img/logo.jpg"
  # faviconfile         : "img/leaf.ico"
  # extracssfiles     : [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.

  cachebuster         : true                          # add the current unix timestamp in query string for cache busting css assets
  dateform            : "Jan 2, 2006"
  dateformfull        : "Mon Jan 2 2006 15:04:05 MST"
  i18n_flags          : false                         # whether to display small country flags for available translations
  noshowreadtime      : false                         # if true, don't show "<x> minutes read" in posts
